# Generated by Django 2.2.6 on 2019-12-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_auto_20191216_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReportesProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.item',),
        ),
    ]
