# Generated by Django 2.2.6 on 2019-10-21 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('EP', 'En proceso'), ('FI', 'Finalizado')], default='PE', max_length=2)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_comandados', to=settings.AUTH_USER_MODEL)),
                ('programador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_testeados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
