# Generated by Django 2.2.6 on 2019-11-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fase',
            field=models.CharField(choices=[('F1', 'Analisis'), ('F2', 'Diseno'), ('F3', 'Generacion de codigo'), ('F4', 'Prueba'), ('F5', 'Mantenimiento')], default='F1', max_length=2),
        ),
    ]
