# Generated by Django 2.2.6 on 2019-10-28 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20191021_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('EP', 'En proceso'), ('FI', 'Finalizado')], default='PE', max_length=2)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_base', to='base.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('EP', 'En proceso'), ('FI', 'Finalizado')], default='PE', max_length=2)),
                ('lineaBase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='base.LineaBase')),
            ],
        ),
    ]
