# Generated by Django 2.2.6 on 2019-12-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_proyecto_fase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
    ]
